services:
  myimage:
    build: .
    ports:
      - "9090:80"
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - valum:/usr/share/nginx/html

volumes:
  valum:

networks:
  backend:
